# Generated by Django 3.2 on 2022-05-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Localidad: ')),
                ('cp', models.CharField(max_length=10, verbose_name='Código Postal: ')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia: ')),
            ],
        ),
    ]
